//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verwaltungsprogramm_Vinothek
{
    using System;

    public partial class Event
    {
        public int ID_Veranstaltung { get; set; }
        public string Name { get; set; }
        public Nullable<int> AnzahlPersonen { get; set; }

        private Nullable<System.DateTime> _datum;
        public Nullable<System.DateTime> Datum
        {
            get { return _datum; }
            set
            {
                if (value < DateTime.Now)
                {
                    _datum = DateTime.Now;
                }
                else
                    _datum = value;
            }
        }

        public string Zeit { get; set; }

        public override string ToString()
        {
            return Name;
        }
    }
}
