//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verwaltungsprogramm_Vinothek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt
    {
        public int ID_Produkt { get; set; }
        public string Name { get; set; }
        public string Art { get; set; }
        public string Qualitätssiegel { get; set; }
        public string Rebsorten { get; set; }
        public string Geschmack { get; set; }
        public Nullable<double> Alkoholgehalt { get; set; }

        private Nullable<int> _jahrgang;
        public Nullable<int> Jahrgang 
        {
            get { return _jahrgang; }
            set 
            {
                if (value <= 1900)
                    _jahrgang = 1900;
                else if (value > DateTime.Now.Year)
                    _jahrgang = DateTime.Now.Year;
                else
                    _jahrgang = value;
            } 
        }
        public string Beschreibung { get; set; }

        private Nullable<double> _preis;
        public Nullable<double> Preis
        {
            get { return _preis; }
            set
            {
                if (value < 0)
                    _preis = 0;                
                else
                    _preis = value;
            }
        }
        public Nullable<bool> Aktiv { get; set; }
        public byte[] Picture { get; set; }
        public byte[] PDF_file { get; set; }
        public int ID_Produzent { get; set; }
    
        public virtual Produzent Produzent { get; set; }

        public override string ToString()
        {
            return Name;
        }
    }
}
