//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verwaltungsprogramm_Vinothek
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VinothekContext : DbContext
    {
        public VinothekContext() : base("name=VinothekContext")
        {
            //Database.SetInitializer<VinothekContext>(new CreateDatabaseIfNotExists<VinothekContext>());
            Database.SetInitializer(new VinothekDBInitializer());
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Benutzer> Benutzer { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<EventPos> EventPos { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<Produkt> Produkt { get; set; }
        public virtual DbSet<Produzent> Produzent { get; set; }
    }    
}
